service: puppeteer-aws-lambda-serverless

frameworkVersion: '3'
useDotenv: true

provider:
  name: aws
  region: us-east-1
  profile: dev
  architecture: x86_64
  environment:
    ENV: ${env:ENV}
  # important for download pdf
  apiGateway:
    binaryMediaTypes:
      - '*/*'

  ecr:
    images:
      puppeteer:
        path: ./

functions:
  app:
    memorySize: 512
    timeout: 29 # ApiGateway max timeout is 30s
    image:
      name: puppeteer
      command:
        - '/app/dist/lambda.handler'
      entryPoint:
        - '/lambda-entrypoint.sh'
    events:
      - httpApi:
          method: '*'
          path: '*'
