service: puppeteer-aws-lambda-serverless

frameworkVersion: '3'
useDotenv: true

provider:
  name: aws
  region: us-east-1
  profile: dev
  memorySize: 512
  architecture: x86_64

  ecr:
    images:
      puppeteer:
        path: ./

functions:
  app:
    image:
      name: puppeteer
      command:
        - '/app/dist/lambda.handler'
      entryPoint:
        - '/lambda-entrypoint.sh'
    events:
      - httpApi:
          method: any
          path: /
