service: puppeteer-aws-lambda-serverless

frameworkVersion: '3'
useDotenv: true

provider:
  name: aws
  region: us-east-1
  profile: dev
  memorySize: 512
  architecture: arm64

  ecr:
    images:
      puppeteer:
        path: ./

functions:
  hello:
    image:
      name: puppeteer
      command:
        - 'dist/lambda.handler'
      entryPoint:
        - '/lambda-entrypoint.sh'
